// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
   show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_Oio-vQg_GNsoGUhfRRBpR5LF81C-BI',
    appId: '1:220507344270:web:852b7a1030c7817b9568df',
    messagingSenderId: '220507344270',
    projectId: 'noteapp-7f20c',
    authDomain: 'noteapp-7f20c.firebaseapp.com',
    storageBucket: 'noteapp-7f20c.firebasestorage.app',
    measurementId: 'G-GMR8K5ZF2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-wdYzI0haOGSjnjDjjTdNbDCBN8muYQ',
    appId: '1:220507344270:android:462bf92edad686d99568df',
    messagingSenderId: '220507344270',
    projectId: 'noteapp-7f20c',
    storageBucket: 'noteapp-7f20c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsL4GFn6rAF_TpRs-NNZYkkrFp3jypFZg',
    appId: '1:220507344270:ios:6fc18fc6a13632959568df',
    messagingSenderId: '220507344270',
    projectId: 'noteapp-7f20c',
    storageBucket: 'noteapp-7f20c.firebasestorage.app',
    iosBundleId: 'com.example.careTutorNoteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsL4GFn6rAF_TpRs-NNZYkkrFp3jypFZg',
    appId: '1:220507344270:ios:6fc18fc6a13632959568df',
    messagingSenderId: '220507344270',
    projectId: 'noteapp-7f20c',
    storageBucket: 'noteapp-7f20c.firebasestorage.app',
    iosBundleId: 'com.example.careTutorNoteTakingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD_Oio-vQg_GNsoGUhfRRBpR5LF81C-BI',
    appId: '1:220507344270:web:807b603a3ab083f79568df',
    messagingSenderId: '220507344270',
    projectId: 'noteapp-7f20c',
    authDomain: 'noteapp-7f20c.firebaseapp.com',
    storageBucket: 'noteapp-7f20c.firebasestorage.app',
    measurementId: 'G-P9R7SJZ25Z',
  );
}
